### ISSUE TITLE
Question: multiple domains at IONOS

### ISSUE THREAD

**Issue by deprecastor** [fabmade/cert-manager-webhook-ionos#10]
Hello @fabmade,

at first. Thank you so much for you work and thx to all other contributes. It works quiet well in my newest cluster. But I have a question and see no other possibility to contact you, but the issues mechanism. I am sorry if that annoys you.

If I have multiple IONOS domains in the same cluster. Can I just install another instance of `cert-manager-webhook-ionos`with different name in the same namespace and another groupName in the values? 

Thanks and have a good day.

**Comment by fabmade** [comment]
Hello @deprecastor,

normally it should work if you simply create another certificate or ingress.

cert for domain 1:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain1-com
spec:
  dnsNames:
    - '*.domain1.com'
  issuerRef:
    name: letsencrypt-ionos-staging
  secretName: domain2-com-tls
```

cert for domain2

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain2-com
spec:
  dnsNames:
    - '*.domain2.com'
  issuerRef:
    name: letsencrypt-ionos-staging
  secretName: domain2-com-tls
```

 let me know if this help you already
